version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./app/:/app/
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=wowsuchsecret
    command: ['gunicorn', 'server:create_app()', '-b', '0.0.0.0:5000', '--reload']
    depends_on:
      - db
      - migrations

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['python3', 'migrations.py']
    depends_on:
      - db

  db:
    image: library/postgres:13-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    ports:
    - 5432:5432

volumes:
  postgres_data: