version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./app/:/app/
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=wowsuchsecret
    command: ['uvicorn', 'server.app:app', '--reload', '--workers', '1', '--host', '0.0.0.0', '--port', '5000']
    depends_on:
      - db

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    command: ['python3', 'migrations.py']
    depends_on:
      - db

  db:
    image: library/postgres:13-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    ports:
    - 5432:5432

volumes:
  postgres_data: