version: "3.8"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
    - ./app/:/app/
    links:
      - db
    ports:
      - "5000:5000"
    env_file:
      - ./app/.env
    depends_on:
      - db

  db:
    image: library/postgres:13-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/.env
    ports:
    - 5432:5432

volumes:
  postgres_data: