version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./app/:/app/
    expose:
      - 5000
    environment:
      - SECRET_KEY=wowsuchsecret
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=bigpassword
    command: ['gunicorn', 'server:create_app()', '-b', '0.0.0.0:5000', '--reload']
    depends_on:
      - db
      - migrations

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['python3', 'migrations.py']
    depends_on:
      - db

  db:
    image: library/postgres:13-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    ports:
    - 5432:5432

  redis:
    image: redis:latest
  
  rabbit:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=bigpassword

  celery_worker:
    scale: 1
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A server.tasks worker -l INFO --uid 1
    volumes:
    - ./app/:/app/
    environment:
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=bigpassword
    depends_on: 
      - rabbit

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A server.tasks beat -l INFO
    volumes:
    - ./app/:/app/
    environment:
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=bigpassword
    depends_on: 
      - rabbit

  nginx:
    build:
      context: ./app/nginx
      dockerfile: Dockerfile.nginx
    ports:
      - 1337:80
    depends_on: 
      - app
    
volumes:
  postgres_data: